on:
  workflow_call:
    inputs:
      MAIN_SLOT_REPO:
        description: Main project repository, using plugin repos
        default:  false
        type: boolean
      GITPULLER_HOST:
        required: true
        type: string
    secrets:
      GITPULLER_KEY:
        required: false
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      id: PullCommand
      uses: fjogeleit/http-request-action@v1
      with:
        url: '${{ inputs.GITPULLER_HOST }}/gitpuller.php'
        customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
        data: '{"repo": "${{ !inputs.MAIN_SLOT_REPO && github.repository || null }}", "GITPULLER_KEY": "${{ secrets.GITPULLER_KEY }}"}'
    - name: Debug
      if: fromJson(steps.PullCommand.outputs.response).debug
      run: echo "${{ toJSON(fromJson(steps.PullCommand.outputs.response).debug) }}"
    - name: Response error
      if: fromJson(steps.PullCommand.outputs.response).code != 200
      run: |
        echo "${{ fromJson(steps.PullCommand.outputs.response).error }}"
        exit 1
    - name: Report
      if: fromJson(steps.PullCommand.outputs.response).code == 200
      run: |
        echo "${{ fromJson(steps.PullCommand.outputs.response).result }}"
        echo "${{ fromJson(steps.PullCommand.outputs.response).error }}"

